apiVersion: v1
kind: Service
metadata:
  name: {{ include "jiralert.fullname" . }}
  namespace: {{ template "jiralert.namespace" . }}
  labels:
    {{- include "jiralert.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 30200
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jiralert.selectorLabels" . | nindent 4 }}
